
#FROM python:3.9-slim
FROM python:3.12.5 
#pour moi

# Définition du répertoire de travail
WORKDIR /app

# Copie du code et des dépendances
COPY . /app
RUN pip install -r requirements.txt

# Exposition du port 8000 (API FastAPI)
EXPOSE 8000

# Commande de lancement
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
