# Image de base
FROM python:3.12-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier et installer les dépendances
COPY docker/requirements/requirements.api.txt .
RUN pip install --no-cache-dir -r requirements.api.txt

# Copier le code
COPY api/ .
COPY src/utils/log_utils.py ./utils/log_utils.py

RUN mkdir -p /app/logs

# Exposer le port FastAPI
EXPOSE 8000

# Lancer l'API avec uvicorn
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]