FROM python:3.12-slim

WORKDIR /app

# Installer uniquement les dépendances de l’ingestion
COPY docker/requirements/requirements.ingest.txt .
RUN pip install --no-cache-dir -r requirements.ingest.txt

# Copier le code source nécessaire
COPY src/ingest/ ./ingest/
COPY src/utils/ ./utils/
COPY app.py .

# Créer les dossiers pour données et logs
RUN mkdir -p /app/raw /app/samples /app/logs

CMD ["python", "app.py", "--mode", "ingest"]
